# Generated by Django 6.1 on 2026-08-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, unique=True),
        ),
    ]
